# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with and , the first terms will be:

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def fiboEvenSum(n):
    firstNum=0;
    secondNum=1;
    sumNum=1;
    evenSum=0;
    
    while secondNum<n:        
        sumNum=firstNum+secondNum;        
        firstNum=secondNum;
        secondNum=sumNum;
        #print(firstNum);
        if secondNum%2==0:
            evenSum=evenSum+secondNum;
            
    print(evenSum);
        
        

n=input('Number to check: ');
fiboEvenSum(int(n));
